name: Verademo-Pipeline

on: [push]

jobs:
  build-pipelinescan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
  
    - name: Build with Maven
      run: mvn clean verify

    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/devops-scanner-java-LATEST.zip
    
    - name: Unzip the Pipeline Scanner
      run: unzip devops-scanner-java-LATEST.zip devops-scanner-java.jar
 
    - name: Engage Ludicrous Speed - Run Pipeline Scan
      run: java -jar devops-scanner-java.jar --jar /home/runner/work/Verademo-master/Verademo-master/target/verademo.war --api_id "${{secrets.VERACODE_API_ID}}" --api_secret_key "${{secrets.VERACODE_API_SECRET}}" --best_practices true
